infisical:
  address: "https://app.infisical.com"
  
auth:
  type: "universal-auth"
  config:
    client-id: "/run/secrets/infisical-universal-auth-client-id"
    client-secret: "/run/secrets/infisical-universal-auth-client-secret"
    remove_client_secret_on_read: false

templates:
  - source-path: /run/secrets/env-template
    destination-path: /infisical-secrets/.env
